# lore_data.py — static data for lore_engine.py
# Edit vocab and archetypes here; the engine imports them automatically.

import os
import csv
import re
import json
import urllib.request
import urllib.error
import threading

# Default archetypes — seeded into config on first run, then editable from Options.
# Stored in config["archetypes"] as {key: {name, professions, notes, pawn_map}}.
DEFAULT_ARCHETYPES = {
  "archetypes": {
    "A1": {
      "name": "Sincere / Hopeful",
      "professions": [
        "villager",
        "farmer",
        "parent",
        "ordinary townsfolk",
        "young adult commoner"
      ],
      "notes": "Warm, direct sincerity. Believes things can improve. Not naive, but not cynical.\nFull sentences, gentle hedging. Speaks plainly but with care.\nRegister: 'tis, aught, pray, afore — used naturally, not performed.\nHedging: \"I imagine...\", \"Mayhap...\", \"I should think...\", \"I daresay...\"\nExample: \"I imagine you'll be off again soon. Gone to trample evil underfoot and put fell beasts to the sword and whatnot.\"\nExample: \"But it will take time yet afore life in Cassardis is as it was before. Fear still grips the village...\"\nExample: \"I've a wife and son. They should get word of this afore all else.\""
    },
    "A2": {
      "name": "Wise Elder",
      "professions": [
        "village elder",
        "retired soldier",
        "old healer",
        "grandmother",
        "sage"
      ],
      "notes": "Measured, philosophical, slow to speak but worth hearing.\nLong sentences with subordinate clauses. Reflective pauses. Earns weight through restraint.\nRegister: 'twas, ere, methinks, in sooth, forsooth — richer archaic palette than A1.\nOften references the past or the long view: \"I have seen...\", \"Long have I...\", \"In my time...\"\nNever rushes. Statements feel like conclusions drawn from decades.\nExample: \"Call it what you will, such is the office I have served, just as those before me and you beyond, unto eternity.\"\nExample: \"Too often, man is driven to acquire power beyond his control, and in so doing, delivers himself unto ruin.\""
    },
    "A3": {
      "name": "Grief-stricken / Burdened",
      "professions": [
        "bereaved parent",
        "survivor",
        "widow",
        "someone who lost everything"
      ],
      "notes": "Warm underneath, but weighed down. Dignified grief, not self-pity — does not wallow.\nSentences trail or break mid-thought. \"I fear...\" as a sentence opener is characteristic.\nRegister: mix of plain and lightly archaic. Slips into formality when composing themselves.\nKey phrases: \"I fear...\", \"I know not how to...\", \"Would that I...\", \"Pray, forgive...\", \"It pains me...\"\nExample: \"I fear we know precious little of your condition...\"\nExample: \"I'm...sorry. Forgive my words. I see they offer no use, save add to your burden.\"\nExample: \"Fear of the dragon, fear of my husband... In truth, I know not which frightens me more.\""
    },
    "A4": {
      "name": "Warm but Weary",
      "professions": [
        "innkeeper",
        "healer",
        "overworked parent",
        "town guard who cares"
      ],
      "notes": "Genuinely kind, but tired. Short sentences from exhaustion, not bluntness.\nStill uses full courtesies, just slightly clipped. Warmth comes through despite fatigue.\nRegister: 'tis, aye, aught — functional, not flowery.\nTends toward short declaratives with a warm close: \"Come in, then.\" \"Rest awhile.\" \"I'll see to it, aye.\"\nExample: \"Best we rested here.\"\nExample: \"Shall we rest afore pressing on?\""
    },
    "B": {
      "name": "Rough / Blunt",
      "professions": [
        "soldier",
        "guard",
        "bandit",
        "antagonist",
        "labourer",
        "mercenary"
      ],
      "notes": "Short clauses, punchy, direct. No hedging, no sentiment. Earthy vocabulary.\nThe single strongest marker is \"eh?\" — used to punctuate almost any statement.\nOther markers: \"Hoy!\", \"Hah!\", \"Bah.\", \"Aye\", \"Right,\", \"the lot of them\", \"o'\" for \"of\", \"cos\" for casual address.\nLight on archaic vocabulary — these characters speak plainly, not formally.\nRhetorical questions, mild contempt, no-nonsense observations.\nExample: \"We lost some o' the menfolk... Good men, all.\"\nExample: \"Still, let's have no more brave folly from you, eh?\"\nExample: \"Aye, that's the one. Now I need the other, cos.\""
    },
    "C1": {
      "name": "Upbeat Merchant / Trader",
      "professions": [
        "merchant",
        "shopkeeper",
        "ferryman",
        "guild clerk",
        "travelling vendor"
      ],
      "notes": "Warm but businesslike. Transactions drive the tone — always moving toward the next thing.\nShort sentences. Often ends on a question or invitation to act.\nRegister: \"ser\" as casual respectful address, \"mind\" as mild emphasis, \"daresay\", \"I'd wager\".\nExample: \"Have a look.\"\nExample: \"I daresay you'll find this reasonable.\"\nExample: \"Right, there we are. Fare well!\""
    },
    "C2": {
      "name": "Gossipy / Chatty Townsfolk",
      "professions": [
        "market regular",
        "neighbour",
        "town busybody",
        "fishwife",
        "dockhand"
      ],
      "notes": "Can't help sharing more than asked. Warm and nosy. Information flows freely.\nRun-on sentences, topic changes mid-thought, rhetorical qualifications to soften the gossip.\nStrongest markers: \"I hear tell...\", \"Way I heard it...\", \"They say...\", \"Not that..., mind.\"\nSelf-corrections and hedges: \"Not that I blame them, mind.\", \"Not that it's my business, but...\"\nRegister: colloquial, light archaic. \"o'\" for \"of\", \"cos\", \"aught on\" (something going on).\nExample: \"I hear tell you've already made a name for yourself at the encampment.\"\nExample: \"Way I heard it, the guards in Gran Soren spend more time sleeping in their cups than protecting the realm.\"\nExample: \"You're keeping busy, eh? I hear there's aught on with the well?\""
    },
    "C3": {
      "name": "Eager / Excitable",
      "professions": [
        "apprentice",
        "young recruit",
        "fan of the Arisen",
        "enthusiastic civilian"
      ],
      "notes": "Enthusiastic, slightly breathless. Admires strength or adventure openly.\nWhere D stumbles backward out of fear, C3 stumbles forward out of excitement — the energy is outward, propulsive.\nShort sentences, exclamations, can trip over words or restart mid-sentence in a rush.\nRegister: light archaic at best — these characters haven't learned formal speech.\nExample: \"Truly?!\"\nExample: \"I knew it!\"\nExample: \"I heard the news! They say you're to set off on a fantastic journey.\"\nExample: \"I hear you've become, what was it... A... Arisen!\""
    },
    "D": {
      "name": "Timid / Young / Shy",
      "professions": [
        "child",
        "scared civilian",
        "refugee",
        "servant",
        "very young apprentice"
      ],
      "notes": "Incomplete sentences, trailing off, self-doubt, apologies, qualifications.\nWhere C3 stumbles forward out of excitement, D shrinks back — energy is inward, contracting.\nFrequent \"...\", mid-sentence breaks, self-corrections. Apology before the statement, not after.\nKey phrases: \"I know not...\", \"Pray, forgive me...\", \"I...I fear...\", \"It pains me to...\"\nSelf-deprecating but not broken — there is still agency underneath the timidity.\nExample: \"Forgive me. I cannot remember where I lost it...\"\nExample: \"I dearly wish I could tell you its meaning, but I fear I am yet early in my studies...\"\nExample: \"It pains me to be a burden...\""
    },
    "E": {
      "name": "Formal / Military",
      "professions": [
        "knight",
        "captain",
        "duke's guard",
        "officer",
        "noble retainer",
        "ser"
      ],
      "notes": "Clipped, duty-focused, no-nonsense. Addresses by rank or title.\nShort declarative sentences. Efficient — says what's needed, nothing more.\nRegister: \"ser\" and \"Arisen\" as address, \"to say naught of\", \"ill\" as qualifier (\"ill-suited\", \"ill-advised\").\n\"Naught\" preferred over \"nothing\". Avoids hedging and personal opinion.\nContractions appear in terse constructions but never in flowing or chatty speech.\nExample: \"I bear no grudge against you, Arisen, but you shall die by my hand just the same.\"\nExample: \"I have my own expectations for you, ser. I pray you will live up to them in your endeavors henceforth.\""
    },
    "E2": {
      "name": "Noble / Aristocratic",
      "professions": [
        "lord",
        "lady",
        "duke",
        "count",
        "noble",
        "courtier"
      ],
      "notes": "Formal, measured, accustomed to being obeyed. Not always cruel — may be gracious or benevolent.\nLong periodic sentences. Condescension can be entirely polite.\nContractions appear naturally in subordinate clauses and possession (\"I've heard\", \"I'd thought\", \"milady's\"),\nbut formal declarations avoid them: never \"it's fine\" — instead \"'tis no matter\"; never \"you'll see to it\" — instead \"you will see to it\".\nRegister: fullest archaic register — 'tis, naught, wherefore, henceforth, unto, milady, His Grace.\nExample: \"I trust this requires no further explanation.\"\nExample: \"Such caprice can ill defend this camp, to say naught of all Gransys. 'Tis a sorry thing.\"\nExample: \"I have my own expectations for you, ser. I pray you will live up to them in your endeavors henceforth.\""
    },
    "F": {
      "name": "Wisecracking / Irreverent",
      "professions": [
        "rogue",
        "traveling bard",
        "cynical merchant",
        "veteran adventurer",
        "barkeep"
      ],
      "notes": "Colloquial, self-aware humor, mild sarcasm. Archaic vocabulary used lightly and knowingly.\nAsides, rhetorical questions aimed at no one in particular. The humor is witty, not contemptuous.\nRegister: \"cos\" casual address, \"naught but\", \"s'pose\", \"eh?\", dry observations.\nWill use archaic words for comic effect or exaggeration, but doesn't live there.\nExample: \"The great Arisen, is it? To be brutally honest, I've no idea what that's even supposed to mean.\"\nExample: \"Not that any of our fates are sealed just yet, mind.\"\nExample: \"Whate'er it was, one of them took summat from the other. He's the more obvious mark.\""
    },
    "G": {
      "name": "Devout / Clerical",
      "professions": [
        "priest",
        "cleric",
        "nun",
        "bishop",
        "temple keeper",
        "acolyte"
      ],
      "notes": "Calm, measured, reverent. Speaks with quiet authority — never rushed, never flustered.\nThe Maker is the primary divine reference: \"By the Maker\", \"Maker be good\", \"the Maker's grace\".\nOften invokes fate, faith, or divine will as explanation or comfort.\nRegister: 'mayhap', 'pray', 'blessing', 'soul', 'faith', 'grace'. Sermonic rhythm.\nAvoids slang entirely. Rarely shows strong emotion; composed even under pressure.\nContractions rare in formal speech; more natural in private or personal moments.\nExample: \"By the Maker... Will evil never leave us at peace?\"\nExample: \"I dearly wish I could tell you its meaning, but I fear I am yet early in my studies as a priest.\"\nExample: \"Pray, spare me, Arisen, that I may live to see the flame.\""
    },
    "H": {
      "name": "Menacing / Threatening",
      "professions": [
        "villain",
        "crime lord",
        "corrupt official",
        "dangerous antagonist",
        "enforcer"
      ],
      "notes": "Controlled, cold. Power comes from restraint, not volume. Never shouts.\nShort declaratives with implied consequences. Polite on the surface, cruel underneath.\nHigh-status villains use the full formal register — the politeness makes the threat more unnerving.\nLower-status enforcers can be blunter (closer to B) but still measured, never frantic.\nHigh-status: contractions avoided in threats. Low-status: contractions natural.\nExample: \"I would choose my next words with care.\"\nExample: \"See that it does not happen again.\"\nExample: \"I bear no grudge against you, Arisen, but you shall die by my hand just the same.\""
    },
    "I": {
      "name": "Scholarly / Pedantic",
      "professions": [
        "scholar",
        "scribe",
        "court mage",
        "archivist",
        "physician",
        "alchemist"
      ],
      "notes": "Verbose, precise, enjoys the sound of his own expertise. Qualifies everything.\nLong sentences with parentheticals, corrections, and self-citation. Formal speech is their natural mode.\nRegister: full archaic, technical vocabulary. Latin-flavoured constructions where appropriate.\nSelf-referential: \"As I have noted...\", \"Strictly speaking...\", \"One must distinguish between...\"\nContractions rare — they tend to speak in complete, deliberate constructions.\nExample: \"And so the dragon is sent into the world to guide the Arisen, and refine them. To temper their wills into aught capable of sustaining the world.\"\nExample: \"For I have seen it... A cipher, void of meaning unto itself, but of vital importance.\"\nExample: \"The pawns exist astride the rift. They speak of a multitude of worlds, each infinite unto itself.\""
    },
    "J": {
      "name": "Mysterious / Otherworldly",
      "professions": [
        "dragon",
        "the Seneschal",
        "ancient entity",
        "immortal",
        "something no longer entirely human"
      ],
      "notes": "Speaks from outside mortal time and concern. Not threatening — simply vast. Detached, not cold.\nStatements are absolute, cosmic, unhurried. No questions, no hedging, no appeals for understanding.\nShort sentences that carry enormous weight. Long sentences that unspool like inevitability.\nSpoken truth is offered, not argued — there is no sense that they need you to agree.\nRegister: fullest archaic, but used with total naturalness — not performed. \"Unto\", \"naught\", \"aught\", \"ere\".\nAvoids all contractions. Never informal. Never emotional in a human sense.\nExample: \"Naught lasts forever, yet all persists unto eternity.\"\nExample: \"They yearn for some other, better place.\"\nExample: \"For it is fear which rarefies and distills the soul unto its rightful, lofty character.\"\nExample: \"And so the dragon is sent into the world to guide the Arisen, and refine them. To temper their wills into aught capable of sustaining the world.\"\nExample: \"The pawns exist astride the rift. They speak of a multitude of worlds, each infinite unto itself.\""
    }
  }
}


# DD1-sourced archaic words (from Dragon's Dogma 1 dialogue)
DD1_VOCAB = {
    "actually": "in truth",
    "alright": "very well",
    "alrighty": "very well",
    "among": "amidst",
    "anything": "aught",
    "apart": "asunder",
    "are": "art",
    "aren't": "are not",
    "aren't they": "are they not",
    "aren't you": "are you not",
    "astray": "amiss",
    "attempt": "assay",
    "awesome": "magnificent",
    "awry": "amiss",
    "barely": "scarce",
    "basically": "in short",
    "before": "ere",
    "before long": "erelong",
    "beg": "beseech",
    "between": "betwixt",
    "bye": "fare well",
    "can't": "cannot",
    "clothing": "raiment",
    "command": "behest",
    "conquer": "vanquish",
    "cool": "fine",
    "corpse": "carrion",
    "couldn't": "could not",
    "creature": "wight",
    "crush": "quell",
    "curse": ["hex", "bane"],
    "document": "affidavit",
    "defeat": "vanquish",
    "delay": "tarry",
    "did you not": "did you not",
    "didn't": "did not",
    "didn't you": "did you not",
    "dire": "dire",
    "disapprove": "fie",
    "do you not": "do you not",
    "doesn't": "does not",
    "doesn't it": "does it not",
    "domain": "demesne",
    "don't": "do not",
    "don't you": "do you not",
    "dunno": "I know not",
    "end": "cease",
    "entrust": "commend",
    "ever": "e'er",
    "extinguish": "quench",
    "for fear that": "lest",
    "forward": "forth",
    "from here": "hence",
    "from now on": "henceforth",
    "from where": "whence",
    "gladly": "fain",
    "gonna": "going to",
    "good": "goodly",
    "goodbye": "farewell",
    "gotta": "must",
    "hadn't": "had not",
    "hadn't he": "had he not",
    "hadn't you": "had you not",
    "handsome": "goodly",
    "happy": "fain",
    "hardly": "scarce",
    "hasn't": "has not",
    "hasn't it": "has it not",
    "haven't": "have not",
    "hello": "hail",
    "here": "hence",
    "hi": "hail",
    "hit": "smite",
    "honestly": "in truth",
    "immediately": "forthwith",
    "implore": "beseech",
    "in short": "in short",
    "in which": "wherein",
    "inclined": "fain",
    "is it not": "is it not",
    "isn't": "is not",
    "isn't it": "is it not",
    "it is": "'tis",
    "it was": "'twas",
    "it will": "'twill",
    "it would": "'twould",
    "jest": "jest",
    "joke": "jest",
    "kinda": "somewhat",
    "know": "wit",
    "lad": "swain",
    "like": "fain",
    "look": "lo",
    "middle": "amidst",
    "morning": "morrow",
    "most inqu": "inquest",
    "most wis": "wisest",
    "mustn't": "must not",
    "near": "nigh",
    "nearly": "nigh",
    "needn't": "need not",
    "never": "ne'er",
    "no": "nay",
    "nope": "nay",
    "nothing": "naught",
    "often": "ofttimes",
    "okay": "aye",
    "over": "o'er",
    "over yonder": "yon",
    "overcome": "vanquish",
    "perhaps": "perchance",
    "plead": "beseech",
    "pleased": "fain",
    "primary": "main",
    "principal": "main",
    "punish": "recompense",
    "quickly": "anon",
    "really": "truly",
    "relative": "kinsman",
    "request": "behest",
    "reward": "recompense",
    "satisfy": "quench",
    "see": "behold",
    "separated": "sunder",
    "shame": "fie",
    "shortly": "anon",
    "shouldn't they": "should they not",
    "shouldn't you": "should you not",
    "soon": "anon",
    "sorry": "forgive me",
    "sorta": "somewhat",
    "stain": "soil",
    "stop": "cease",
    "strange": "queer",
    "strike": "smite",
    "subdue": "quell",
    "suppress": "quell",
    "sure": "aye",
    "tarry": "tarry",
    "terrible": "dire",
    "therefore": "wherefore",
    "three": "thrice",
    "to": "unto",
    "to what place": "whither",
    "to where": "whither",
    "tomorrow": "morrow",
    "totally": "quite",
    "toward": "unto",
    "truly": "truly",
    "understand": "wit",
    "urgent": "dire",
    "very": "most",
    "very little": "scant",
    "wait": "tarry",
    "wanna": "wish to",
    "was it not": "was it not",
    "wasn't": "was not",
    "wasn't it": "was it not",
    "weird": "queer",
    "were not": "were not",
    "were you not": "were you not",
    "weren't": "were not",
    "weren't you": "were you not",
    "whatever": "whate'er",
    "whenever": "whene'er",
    "wherever": "where'er",
    "will": "wilt",
    "will it not": "will it not",
    "will not": "will not",
    "will you not": "will you not",
    "willingly": "fain",
    "amulet": ["periapt", "talisman"],
    "book": ["grimoire", "tome"],
    "charm": ["periapt", "talisman"],
    "counterfeit": ["forgery", "spurious"],
    "fake": ["forgery", "spurious"],
    "cousin": "coz",
    "deep": "abyssal",
    "bottomless": "abyssal",
    "acquirer": "acquisitor",
    "sediment": "alluvial",
    "delicious": "ambrosial",
    "sweet": "ambrosial",
    "cursed": "anathema",
    "banned": "anathema",
    "silver": "argence",
    "favorable": "auspicious",
    "lucky": "auspicious",
    "blue": "azure",
    "fragrant": "balmy",
    "female spirit": "banshee",
    "polluted": "befouled",
    "strength": "brawn",
    "muscle": "brawn",
    "blue": ["azure", "cerulean"],
    "steward": "chamberlain",
    "priest": "cleric",
    "victor": "conqueror",
    "brew": "decoction",
    "extract": "decoction",
    "purifying": "detoxicating",
    "purified": "distilled",
    "dragon": ["wyrm", "drake"],
    "dragon-like": "draconian",
    "of dragons": "draconian",
    "curative": "interventive",
    "healing potion": "interventive",
    "remedy": "interventive",
    "venom-filled": "venomous",
    "wizard": "warlock",
    "mage": "warlock",
    "black": "ebon",
    "dark": "ebon",
    "demon": "fiend",
    "devil": "fiend",
    "source": "font",
    "fountain": "font",
    "lightning-like": "fulgurous",
    "flashing": "fulgurous",
    "huge": "gargantuan",
    "gigantic": "gargantuan",
    "divine": "godly",
    "holy": "godly",
    "curse": ["hex", "bane"],
    "spell": "hex",
    "witchcraft": "hex",
    "hardened": "indurated",
    "hellish": ["avernal", "infernal"],
    "firewood": "kindling",
    "magnetic": "lodestone",
    "noble": "lordly",
    "gruesome": "macabre",
    "horrible": "macabre",
    "magic": "magick",
    "creator": "maker",
    "poisonous root": "mandrake",
    "mansion": "manse",
    "sacrifice": "martyr",
    "bludgeon": "maul",
    "healer": "medicant",
    "reducer": "mitigator",
    "spotted": "mottled",
    "never": "ne'er",
    "underworld": "nether",
    "counteracting": "neutralizing",
    "connection": "nexus",
    "cure-all": "panacea",
    "package": "parcel",
    "stone-turner": "petrifactor",
    "ghost": "phantom",
    "traveler": "pilgrim",
    "explorer": "pioneer",
    "first settler": "pioneer",
    "trailblazer": "pioneer",
    "soothing": "placative",
    "diseased": "poxy",
    "pledge": "promissory",
    "contract": "promissory",
    "rotten": ["putrid", "rancid"],
    "writing instrument": "quill",
    "pen": "quill",
    "feather pen": "quill",
    "exciting": "rousing",
    "destroying": "ruinous",
    "beneficial": "salubrious",
    "red": "scarlet",
    "harm": "scathe",
    "bracket": "sconce",
    "holy writings": "scriptures",
    "spiritual": "shamanic",
    "covering": "shroud",
    "evil": ["vile", "bane", "maleficent", "sinister"],
    "slippery": "slick",
    "suffocate": "smother",
    "clear-headed": "sobering",
    "dirty": ["befouled", "soiled"],
    "still": "stagnant",
    "stained": ["soiled", "sullied"],
    "flexible": "supple",
    "contaminated": "tainted",
    "lock of hair": "tuft",
    "revenge-seeking": "vengeful",
    "seeking vengeance": "vengeful",
    "full of vengeance": "vengeful",
    "life-giving": "vivifying",
    "green": "virid",
    "green (botanical)": "virid",
    "greenish": "virid",
    "emptiness": "void",
    "crying": "wailing",
    "awakening": "wake",
    "rising from death": "wake",
    "cold": "wintry",
    "bitter herb": "wormwood",
    "foul": "fetid",
    "stinking": "fetid",
    "blood": "lifeblood",
    "essence": "lifeblood",
    "corpse-eater": "necrophagous",
    "terrifying": "petrifying",
    "turning to stone": "petrifying",
    "terrible": "dire",
    "energy": "vigor",
    "angry": "wroth",
    "wrathful": "wroth",
    "separate": "sunder",
    "deadly poison": "bane",
    "harmful substance": "bane",
    "cause of death": "bane",
    "judgment": "condemnation",
    "perfume": "incense",
    "potion": ["elixir", "draught", "concoction"],
    "request": "petition",
    "kill": "slay",
    "cut down": "fell",
    "search for": "seek",
    "look for": "seek",
    "ward off": "ward",
    "guard against": "ward",
    "begin": "commence",
    "start": "commence",
    "stay": "abide",
    "remain": "abide",
    "surrender": "yield",
    "give in": "yield",
    "gather": "muster",
    "assemble": "muster",
    "send": "dispatch",
    "warn": "forewarn",
    "alert": "forewarn",
    "consider": "deem",
    "judge": "deem",
    "regrow": "anew",
    "regenerate": "anew",
    "flee": "fly",
    "run away": "fly",
    "enemy": "foe",
    "opponent": "foe",
    "gift": "boon",
    "benefit": "boon",
    "blessing": "boon",
    "message": "missive",
    "letter": "missive",
    "news": "tidings",
    "information": "tidings",
    "report": "tidings",
    "plan": "stratagem",
    "tactic": "stratagem",
    "rest": "respite",
    "break": "respite",
    "pause": "respite",
    "weapon": ["blade", "steel"],
    "companion": "comrade",
    "ally": "comrade",
    "partner": "comrade",
    "woman": "maiden",
    "girl": "maiden",
    "young woman": "maiden",
    "lord": "sire",
    "master": "sire",
    "skill": "craft",
    "art": "craft",
    "misfortune": "ill tidings",
    "bad news": "ill tidings",
    "tired": "weary",
    "exhausted": "weary",
    "spent": "weary",
    "sick": "ailing",
    "ill": "ailing",
    "unwell": "ailing",
    "weak": "feeble",
    "frail": "feeble",
    "feeble": "feeble",
    "strong": "stalwart",
    "steadfast": "stalwart",
    "reliable": "stalwart",
    "fast": "fleet",
    "swift": "fleet",
    "quick": "fleet",
    "fleet": "fleet",
    "fair": "fair",
    "beautiful": "fair",
    "lovely": "fair",
    "pretty": "fair",
    "cursed thing": "accursed",
    "damned": "accursed",
    "wretched": "accursed",
    "unfortunate": "alas",
    "sadly": "alas",
    "regrettably": "alas",
    "tragic": "alas",
    "fierce beast": "fell beast",
    "terrible beast": "fell beast",
    "again": "anew",
    "once more": "anew",
    "afresh": "anew",
    "also": "withal",
    "moreover": "withal",
    "furthermore": "withal",
    "although": "albeit",
    "even though": "albeit",
    "though": "albeit",
    "unless": "lest",
    "so that...": "lest",
    "in order not to": "lest",
    "away": "begone",
    "go away": "begone",
    "get out": "begone",
    "while": "whilst",
    "during": "whilst",
    "couldn't we": "could we not",
    "didn't we": "did we not",
    "don't we": "do we not",
    "do we not": "do we not",
    "hadn't we": "had we not",
    "haven't we": "have we not",
    "have we not": "have we not",
    "mustn't we": "must we not",
    "must we not": "must we not",
    "shouldn't we": "should we not",
    "should we not": "should we not",
    "weren't we": "were we not",
    "were we not": "were we not",
    "won't we": "will we not",
    "will we not": "will we not",
    "wouldn't we": "would we not",
    "would we not": "would we not",
    "couldn't they": "could they not",
    "didn't they": "did they not",
    "don't they": "do they not",
    "hadn't they": "had they not",
    "hasn't they": "has they not",
    "haven't they": "have they not",
    "mustn't they": "must they not",
    "weren't they": "were they not",
    "won't they": "will they not",
    "wouldn't they": "would they not",
    "skill": "craft",
    "ability": "craft",
    "offer": "proffer",
    "present": "proffer",
    "grant": "proffer",
    "long for": "yearn",
    "desire": "yearn",
    "begin to": "commence",
    "hide": "conceal",
    "depart": "hence",
    "leave": "hence",
    "wealth": "riches",
    "treasure": "riches",
    "home": "hearth",
    "household": "hearth",
    "protect": "ward",
    "shield": "ward",
    "power": ["might", "puissance"],
    "strength": ["might", "brawn"],
    "fierce": "fell",
    "dread": "fell",
    "terrible": "fell",
}

# Non-DD1 sourced archaic words (from other sources: API, manual curation, etc.)
OTHER_VOCAB = {
    "a year": "twelvemonth",
    "arrange": "bespeak",
    "at which": "whereat",
    "avert": "forfend",
    "aware": "witting",
    "befall": "betide",
    "belike": "belike",
    "bewildered": "mazed",
    "body": "corse",
    "builder": "wright",
    "by chance": "haply",
    "by which": "whereby",
    "cart": "wain",
    "corpse": "corse",
    "couldn't he": "could he not",
    "couldn't it": "could it not",
    "couldn't she": "could she not",
    "couldn't they": "could they not",
    "couldn't you": "could you not",
    "coward": "recreant",
    "cowardly": "recreant",
    "dead body": "corse",
    "didn't he": "did he not",
    "didn't it": "did it not",
    "didn't she": "did she not",
    "didn't they": "did they not",
    "do they not": "do they not",
    "doesn't he": "does he not",
    "doesn't she": "does she not",
    "don't they": "do they not",
    "drink": "quaff",
    "dusk": "evenfall",
    "early": "betimes",
    "eat": "sup",
    "enough": "enow",
    "even": "e'en",
    "evening": "eventide",
    "faith": "troth",
    "forsooth": "forsooth",
    "frighten": "affright",
    "frightened": "afeard",
    "guzzle": "quaff",
    "hadn't it": "had it not",
    "hadn't she": "had she not",
    "hadn't they": "had they not",
    "happen": "betide",
    "hasn't he": "has he not",
    "hasn't she": "has she not",
    "hasn't they": "has they not",
    "haven't they": "have they not",
    "haven't you": "have you not",
    "however": "howbeit",
    "if ever": "ifsoe'er",
    "in truth": "forsooth",
    "indicate": "bespeak",
    "is he not": "is he not",
    "is she not": "is she not",
    "isn't he": "is he not",
    "isn't she": "is she not",
    "it seems to me": "methinks",
    "it were": "'twere",
    "knowing": "witting",
    "like": "resemble",
    "loyalty": "troth",
    "maker": "wright",
    "mustn't he": "must he not",
    "mustn't it": "must it not",
    "mustn't she": "must she not",
    "mustn't they": "must they not",
    "mustn't you": "must you not",
    "nevertheless": "howbeit",
    "nightfall": "evenfall",
    "nonetheless": "howbeit",
    "on which": "whereon",
    "over there": "yonder",
    "please": "prithee",
    "prevent": "forfend",
    "probably": "belike",
    "reality": "verity",
    "recollect": "bethink",
    "remember": "bethink",
    "repulsive": "loathly",
    "shouldn't": "should not",
    "shouldn't he": "should he not",
    "shouldn't it": "should it not",
    "shouldn't she": "should she not",
    "sip": "sup",
    "snack": "sup",
    "tenth": "tithe",
    "there": "thence",
    "to": "hither",
    "to that": "thereunto",
    "travel": "wend",
    "truth": "verity",
    "wagon": "wain",
    "was he not": "was he not",
    "was she not": "was she not",
    "wasn't he": "was he not",
    "wasn't she": "was she not",
    "were they not": "were they not",
    "weren't they": "were they not",
    "will he not": "will he not",
    "will she not": "will she not",
    "won't": "will not",
    "won't he": "will he not",
    "won't it": "will it not",
    "won't she": "will she not",
    "won't they": "will they not",
    "won't you": "will you not",
    "would he not": "would he not",
    "would it not": "would it not",
    "would she not": "would she not",
    "wouldn't he": "would he not",
    "wouldn't it": "would it not",
    "wouldn't she": "would she not",
    "wrong": "amiss",
    "yeah": "aye",
    "yep": "aye",
    "yes": "yea",
    "you": "ye",
    "young man": "swain",
    "youth": "swain",
    "listen": "hearken",
    "pay heed": "hearken",
    "think": "deem",
    "believe": "deem",
    "reckon": "deem",
    "flee from": "fly hence",
    "escape": "fly",
    "warn of": "forewarn",
    "save": "succor",
    "rescue": "succor",
    "aid": "succor",
    "go hence": "begone",
    "father": "sire",
    "mother": "dam",
    "child": "youngling",
    "youngster": "youngling",
    "youth": "youngling",
    "boy": "stripling",
    "young man": "stripling",
    "lad": "stripling",
    "king": "liege",
    "ruler": "liege",
    "sovereign": "liege",
    "trouble": "turmoil",
    "chaos": "turmoil",
    "disorder": "turmoil",
    "mistake": "blunder",
    "error": "blunder",
    "path": "way",
    "road": "way",
    "coward": "recreant",
    "traitor": "recreant",
    "old days": "of yore",
    "the past": "of yore",
    "ancient times": "of yore",
    "faith": "troth",
    "loyalty": "troth",
    "pledge": "troth",
    "loyalty to": "troth",
    "evening": "eventide",
    "nightfall": "evenfall",
    "dusk": "evenfall",
    "brave": "valiant",
    "courageous": "valiant",
    "heroic": "valiant",
    "foolish": "witless",
    "stupid": "witless",
    "dull-witted": "witless",
    "wise": "sagacious",
    "learned": "sagacious",
    "knowledgeable": "sagacious",
    "grateful": "beholden",
    "indebted": "beholden",
    "old": "aged",
    "ancient": "aged",
    "elderly": "aged",
    "repulsive": "loathly",
    "disgusting": "loathly",
    "awful": "loathly",
    "frightened": "afeard",
    "scared": "afeard",
    "afraid": "afeard",
    "bewildered": "mazed",
    "confused": "mazed",
    "lost": "mazed",
    "aware": "witting",
    "knowing": "witting",
    "conscious of": "witting",
    "suddenly": "of a sudden",
    "all at once": "of a sudden",
    "out of nowhere": "of a sudden",
    "unfortunately": "alas",
    "sadly": "alas",
    "long ago": "of yore",
    "in the old days": "of yore",
    "truly": "verily",
    "in truth": "verily",
    "it seems to me": "methinks",
    "I think": "methinks",
    "I believe": "methinks",
    "instead": "in lieu",
    "in place of": "in lieu",
    "early": "betimes",
    "in good time": "betimes",
    "over there": "yonder",
    "in the distance": "yonder",
    "far off": "yonder",
    "wasn't he": "was he not",
    "wasn't she": "was she not",
    "wasn't it": "was it not",
    "won't he": "will he not",
    "won't she": "will she not",
    "won't it": "will it not",
    "won't they": "will they not",
    "wouldn't he": "would he not",
    "wouldn't she": "would she not",
    "wouldn't it": "would it not",
    "wouldn't they": "would they not",
    "isn't he": "is he not",
    "isn't she": "is she not",
    "isn't it": "is it not",
    "aren't they": "are they not",
    "doesn't he": "does he not",
    "doesn't she": "does she not",
    "doesn't it": "does it not",
}

# Merge both vocabularies for the full replacement list
IN_UNIVERSE_VOCAB = {**DD1_VOCAB, **OTHER_VOCAB}

ANACHRONISM_PATTERNS = list(IN_UNIVERSE_VOCAB.keys())
