name: CSV Validation

on:
  pull_request:
    paths:
      - 'English/**.csv'
      - 'Portuguese (Brazil)/**.csv'
      - 'Simplified Chinese/**.csv'
      - 'Spanish/**.csv'
      - 'Traditional Chinese/**.csv'
      - 'Viet/**.csv'

  workflow_dispatch:
  push:
    paths:
      - 'English/**.csv'
      - 'Portuguese (Brazil)/**.csv'
      - 'Simplified Chinese/**.csv'
      - 'Spanish/**.csv'
      - 'Traditional Chinese/**.csv'
      - 'Viet/**.csv'
jobs:
  validate_csvs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Needed for git diff

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: python -m pip install --upgrade pip

      - name: Run CSV validation
        working-directory: English
        run: |
          python generate_gmd.py --ci